image: maven:3.8.4-jdk-11  

pipelines:
  default:
    - step:
        name: Create and Execute the Script which updates the POM
        script:
          - source config.env
          
          - git config --global user.email ${BITBUCKET_EMAIL}
          - git remote add dev https://raslenouarghi:${BITBUCKET_TOKEN}@bitbucket.org/ci-cd-pipe/mulesoft_cicd.git         
          - |
            touch update-pom.sh
            
            echo '#!/bin/bash' > update-pom.sh
            echo 'source config.env' >> update-pom.sh
            echo 'ANYPOINT_USERNAME="${ANYPOINT_USERNAME}"' >> update-pom.sh
            echo 'ANYPOINT_PASSWORD="${ANYPOINT_PASSWORD}"' >> update-pom.sh
            echo 'BUSINESS_GROUP="${BUSINESS_GROUP}"' >> update-pom.sh
            echo 'PLUGIN_EXISTS=$(grep -c "<groupId>org.mule.tools.maven</groupId>" pom.xml)' >> update-pom.sh
            echo 'if [ "$PLUGIN_EXISTS" -eq 0 ]; then' >> update-pom.sh
            echo '  CONFIGURATION="<plugin>\n<groupId>org.mule.tools.maven</groupId>\n<artifactId>mule-maven-plugin</artifactId>\n<version>\${mule.maven.plugin.version}</version>\n<extensions>true</extensions>\n<configuration>\n<cloudHubDeployment>\n<uri>https://anypoint.mulesoft.com/</uri>\n<muleVersion>4.7.0</muleVersion>\n<username>${ANYPOINT_USERNAME}</username>\n<password>${ANYPOINT_PASSWORD}</password>\n<applicationName>${BITBUCKET_BRANCH}</applicationName>\n<businessGroup>${BUSINESS_GROUP}</businessGroup>\n<environment>${BITBUCKET_BRANCH}</environment>\n<workers>1</workers>\n<objectStoreV2>true</objectStoreV2>\n</cloudHubDeployment>\n</configuration>\n</plugin>"' >> update-pom.sh
            echo '  sed -i "/<\/plugins>/i $CONFIGURATION" pom.xml' >> update-pom.sh

            echo '  git add pom.xml' >> update-pom.sh
            echo '  git commit -m "Update pom.xml with cloudHubDeployment configuration"' >> update-pom.sh
            echo '  git push dev ${BITBUCKET_BRANCH}' >> update-pom.sh

            echo 'fi' >> update-pom.sh

            chmod +x update-pom.sh

            ls -la
            cat update-pom.sh

            ./update-pom.sh

          

    - step:
        name: Build
        caches:
          - maven
        script:
          - mvn clean package  

    - step:
        name: Deploy to CloudHub
        script:
          - mvn deploy -DmuleDeploy -DskipTests  

    
