image: maven:3.8.4-jdk-11  # Docker image to use for the build environment

pipelines:
  default:
    - step:
        name: Create and Run Update Script
        script:
          - git config --global user.email "raslenouarghi2018@gmail.com"
          - git config --global user.name "raslen ouarghi"

          - |
            # Create the update-pom.sh file
            touch update-pom.sh

            # Append the shebang to the script
            echo '#!/bin/bash' > update-pom.sh

            # Add the logic to check if the plugin configuration exists and add it if not
            echo 'PLUGIN_EXISTS=$(grep -c "<groupId>org.mule.tools.maven</groupId>" pom.xml)' >> update-pom.sh
            echo 'if [ "$PLUGIN_EXISTS" -eq 0 ]; then' >> update-pom.sh
            echo '  CONFIGURATION="<plugin>\n<groupId>org.mule.tools.maven</groupId>\n<artifactId>mule-maven-plugin</artifactId>\n<version>\${mule.maven.plugin.version}</version>\n<extensions>true</extensions>\n<configuration>\n<cloudHubDeployment>\n<uri>https://anypoint.mulesoft.com/</uri>\n<muleVersion>4.7.0</muleVersion>\n<username>Raslen</username>\n<password>Warghui110</password>\n<applicationName>cicdtest-staging</applicationName>\n<businessGroup>ITMMA</businessGroup>\n<environment>Staging</environment>\n<workers>1</workers>\n<objectStoreV2>true</objectStoreV2>\n</cloudHubDeployment>\n</configuration>\n</plugin>"' >> update-pom.sh
            echo '  sed -i "/<\/plugins>/i $CONFIGURATION" pom.xml' >> update-pom.sh

            # Git commands are only executed if the plugin is added
            echo '  git add pom.xml' >> update-pom.sh
            echo '  git commit -m "Update pom.xml with cloudHubDeployment configuration"' >> update-pom.sh
            echo '  git push dev developer' >> update-pom.sh

            echo 'fi' >> update-pom.sh

            # Make the script executable
            chmod +x update-pom.sh

            # Verify the script creation
            ls -la
            cat update-pom.sh

            # Run the script to modify pom.xml
            ./update-pom.sh

          # Configure Git remote
          - git remote add dev https://raslenouarghi2018:ATBBY9M9rsJJWGcfSJywrLPxAbsw8F5564A7@bitbucket.org/devops_project/mulesoft_cicd.git

    - step:
        name: Build
        caches:
          - maven
        script:
          - mvn clean package  # Run Maven to clean and package the code

    - step:
        name: Deploy to CloudHub
        script:
          - mvn deploy -DmuleDeploy -DskipTests  # Deploy the code to CloudHub

    - step:
        name: Failure Message
        trigger: manual  # Triggered manually if previous steps fail
        script:
          - echo 'Build or deployment failed.'  # Log a message if the build or deployment fails