image: maven:3.8.4-jdk-11  # Docker image to use for the build environment

pipelines:
  default:
    - step:
        name: Build
        caches:
          - maven
        script:
          - mvn clean package  # Run Maven to clean and package the code

    - step:
        name: Deploy to CloudHub
        script:
          - mvn -X deploy -DmuleDeploy -DskipTests \
              -Dmule.maven.plugin.version=4.7.0 \
              -Dcloudhub.uri=https://anypoint.mulesoft.com/ \
              -Dcloudhub.muleVersion=4.7.0 \
              -Dcloudhub.username=Feriel \
              -Dcloudhub.password=Feriel123** \
              -Dcloudhub.applicationName=projectcicd \
              -Dcloudhub.businessGroup=ITMMA \
              -Dcloudhub.environment=Develop \
              -Dcloudhub.workers=1 \
              -Dcloudhub.objectStoreV2=true

    - step:
        name: Failure Message
        trigger: manual  # Triggered manually if previous steps fail
        script:
          - echo 'Build or deployment failed.'  # Log a message if the build or deployment fails
