image: maven:3.8.4-jdk-11  # Docker image to use for the build environment

pipelines:
  default:
    - step:
        name: Build
        caches:
          - maven
        script:
          - mvn clean package  # Run Maven to clean and package the code

    - step:
        name: Deploy to CloudHub
        script:
          - mvn -X deploy -DmuleDeploy -DskipTests  # Deploy the code to CloudHub

    - step:
        name: Failure Message
        trigger: manual  # Triggered manually if previous steps fail
        script:
          - echo 'Build or deployment failed.'  # Log a message if the build or deployment fails
